name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nicknovitski/nix-develop@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in bin/*; do
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
